on:
  push:
    branches: ["main"]
  release:
    types: [published, created, edited, released, prereleased]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install python packages
        run: |
          pip install PyGithub pandas
      - name: regenerate apps.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python generate_json.py -t ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated Change
          commit_options: '--no-verify --signoff'
          file_pattern: 'apps.json index.html bundleId.csv icons/*'
          push_options: '--force'
